// Generated by clients/obsidian/scripts/build-artifact.js. Do not edit by hand.
"use strict";

const __moduleFactories = Object.freeze({
  "/protocol/src/generated/protocol-v1.js": function(module, exports, require) {
    "use strict";
    // @generated by `cargo run -p autocomplete-protocol --bin export_client_artifacts -- <output-dir>`.
    // Source of truth: crates/autocomplete-protocol.

    module.exports = Object.freeze({
      PROTOCOL_VERSION: 1,
      HEALTH_PATH: "/health",
      AUTOCOMPLETE_PATH: "/v1/autocomplete",
      CANCEL_PATH_PREFIX: "/v1/cancel/",
      RELOAD_PATH: "/v1/reload",
      AUTOCOMPLETE_MODE_INLINE_TAB: "inline_tab",
      TRIGGER_IDLE: "idle",
      TRIGGER_MANUAL: "manual",
      TRIGGER_DOCUMENT_CHANGE: "document_change",
      RESPONSE_OK: "ok",
      RESPONSE_NO_SUGGESTION: "no_suggestion",
      RESPONSE_CANCELLED: "cancelled",
      RESPONSE_ERROR: "error"
    });
  },
  "/protocol/src/client.js": function(module, exports, require) {
    "use strict";

    const { randomUUID } = require("node:crypto");
    const protocol = require("./generated/protocol-v1.js");

    const DEFAULT_BROKER_URL = "http://127.0.0.1:32145";
    const DEFAULT_DEBOUNCE_MS = 500;
    const DEFAULT_MAX_CONTEXT_CHARS = 4_700;
    const DEFAULT_MAX_COMPLETION_CHARS = 180;
    const DEFAULT_DEADLINE_MS = 2_500;

    function defaultClientSettings(overrides = {}) {
      return {
        brokerUrl: DEFAULT_BROKER_URL,
        debounceMs: DEFAULT_DEBOUNCE_MS,
        maxContextChars: DEFAULT_MAX_CONTEXT_CHARS,
        maxCompletionChars: DEFAULT_MAX_COMPLETION_CHARS,
        deadlineMs: DEFAULT_DEADLINE_MS,
        ...withoutUndefined(overrides),
      };
    }

    function withoutUndefined(object) {
      return Object.fromEntries(
        Object.entries(object).filter(([, value]) => value !== undefined),
      );
    }

    function normalizeBrokerUrl(brokerUrl = DEFAULT_BROKER_URL) {
      return String(brokerUrl || DEFAULT_BROKER_URL).replace(/\/+$/, "");
    }

    function protocolUrl(brokerUrl, path) {
      return `${normalizeBrokerUrl(brokerUrl)}${path}`;
    }

    function clampInteger(value, fallback, { min = 0, max = Number.MAX_SAFE_INTEGER } = {}) {
      const numeric = Number(value);
      if (!Number.isFinite(numeric)) {
        return fallback;
      }
      return Math.min(max, Math.max(min, Math.trunc(numeric)));
    }

    function contextAroundText(text, offset, maxContextChars) {
      const source = String(text ?? "");
      const safeOffset = clampInteger(offset, 0, { min: 0, max: source.length });
      const maxChars = clampInteger(maxContextChars, DEFAULT_MAX_CONTEXT_CHARS, { min: 0 });
      const prefixBudget = Math.ceil(maxChars * 0.75);
      const suffixBudget = Math.max(0, maxChars - prefixBudget);
      return {
        prefix: source.slice(Math.max(0, safeOffset - prefixBudget), safeOffset),
        suffix: source.slice(safeOffset, Math.min(source.length, safeOffset + suffixBudget)),
      };
    }

    function lineCharacterFromOffset(text, offset) {
      const source = String(text ?? "");
      const safeOffset = clampInteger(offset, 0, { min: 0, max: source.length });
      let line = 0;
      let lineStart = 0;
      for (let index = 0; index < safeOffset; index += 1) {
        if (source.charCodeAt(index) === 10) {
          line += 1;
          lineStart = index + 1;
        }
      }
      return { line, character: safeOffset - lineStart, offset: safeOffset };
    }

    function createAutocompleteRequest({
      requestId = randomUUID(),
      clientName,
      clientVersion = "0.1.0",
      documentUri,
      languageId,
      documentVersion = 0,
      cursor,
      context,
      options = {},
    }) {
      if (!clientName) {
        throw new Error("clientName is required");
      }
      if (!documentUri) {
        throw new Error("documentUri is required");
      }
      if (!languageId) {
        throw new Error("languageId is required");
      }
      if (!cursor) {
        throw new Error("cursor is required");
      }
      if (!context) {
        throw new Error("context is required");
      }

      return {
        protocol_version: protocol.PROTOCOL_VERSION,
        request_id: requestId,
        client: {
          name: String(clientName),
          version: String(clientVersion || "0.1.0"),
        },
        document: {
          uri: String(documentUri),
          language_id: String(languageId),
          version: clampInteger(documentVersion, 0, { min: 0 }),
        },
        cursor: {
          line: clampInteger(cursor.line, 0, { min: 0 }),
          character: clampInteger(cursor.character, 0, { min: 0 }),
          offset: clampInteger(cursor.offset, 0, { min: 0 }),
        },
        context: {
          prefix: String(context.prefix ?? ""),
          suffix: String(context.suffix ?? ""),
          selected_text: String(context.selected_text ?? ""),
        },
        options: {
          mode: protocol.AUTOCOMPLETE_MODE_INLINE_TAB,
          max_chars: clampInteger(options.max_chars, DEFAULT_MAX_COMPLETION_CHARS, { min: 1 }),
          deadline_ms: clampInteger(options.deadline_ms, DEFAULT_DEADLINE_MS, { min: 1 }),
          trigger: options.trigger || protocol.TRIGGER_IDLE,
        },
      };
    }

    function insertTextFromResponse(response, requestId) {
      if (!response || response.status !== protocol.RESPONSE_OK) {
        return null;
      }
      if (requestId && response.request_id !== requestId) {
        return null;
      }
      const insertText = response.insert_text;
      return typeof insertText === "string" && insertText.length > 0 ? insertText : null;
    }

    class BrokerClient {
      constructor({ brokerUrl = DEFAULT_BROKER_URL, fetchImpl } = {}) {
        const resolvedFetch = fetchImpl === undefined ? globalThis.fetch : fetchImpl;
        if (typeof resolvedFetch !== "function") {
          throw new Error("fetch is not available; pass fetchImpl when constructing BrokerClient");
        }
        this.brokerUrl = normalizeBrokerUrl(brokerUrl);
        this.fetchImpl = fetchImpl === undefined ? resolvedFetch.bind(globalThis) : fetchImpl;
      }

      async autocomplete(request, { signal } = {}) {
        const response = await this.fetchImpl(protocolUrl(this.brokerUrl, protocol.AUTOCOMPLETE_PATH), {
          method: "POST",
          headers: { "content-type": "application/json" },
          body: JSON.stringify(request),
          signal,
        });
        return response.json();
      }

      async cancel(requestId, { signal } = {}) {
        const response = await this.fetchImpl(
          protocolUrl(this.brokerUrl, `${protocol.CANCEL_PATH_PREFIX}${encodeURIComponent(requestId)}`),
          { method: "POST", signal },
        );
        return response.json();
      }
    }

    class BrokerAutocompleteSession {
      constructor({ client, debounceMs = DEFAULT_DEBOUNCE_MS } = {}) {
        if (!client) {
          throw new Error("BrokerAutocompleteSession requires a client");
        }
        this.client = client;
        this.debounceMs = clampInteger(debounceMs, DEFAULT_DEBOUNCE_MS, { min: 0 });
        this.sequence = 0;
        this.current = null;
      }

      complete(request, { signal } = {}) {
        this.cancelCurrent("stale_request_replaced");

        const sequence = ++this.sequence;
        const controller = new AbortController();
        let externalAbortCleanup = () => {};

        const promise = new Promise((resolve, reject) => {
          const pending = {
            sequence,
            request,
            requestId: request.request_id,
            controller,
            timer: null,
            settled: false,
            resolve: (value) => {
              if (pending.settled) {
                return;
              }
              pending.settled = true;
              externalAbortCleanup();
              resolve(value);
            },
            reject: (error) => {
              if (pending.settled) {
                return;
              }
              pending.settled = true;
              externalAbortCleanup();
              reject(error);
            },
          };

          if (signal) {
            if (signal.aborted) {
              pending.resolve(null);
              return;
            }
            const onAbort = () => this.cancelPending(pending, "host_cancelled");
            signal.addEventListener("abort", onAbort, { once: true });
            externalAbortCleanup = () => signal.removeEventListener("abort", onAbort);
          }

          this.current = pending;
          pending.timer = setTimeout(() => this.sendPending(pending), this.debounceMs);
        });

        return promise;
      }

      cancelCurrent(reason = "cancelled") {
        if (!this.current) {
          return;
        }
        this.cancelPending(this.current, reason);
      }

      cancelPending(pending, reason = "cancelled") {
        if (pending.timer) {
          clearTimeout(pending.timer);
          pending.timer = null;
        }
        if (!pending.controller.signal.aborted) {
          pending.controller.abort(reason);
        }
        if (this.current === pending) {
          this.current = null;
        }
        this.client.cancel(pending.requestId).catch(() => {});
        pending.resolve(null);
      }

      async sendPending(pending) {
        pending.timer = null;
        if (this.current !== pending || pending.controller.signal.aborted) {
          pending.resolve(null);
          return;
        }

        try {
          const response = await this.client.autocomplete(pending.request, {
            signal: pending.controller.signal,
          });
          if (this.current !== pending || pending.controller.signal.aborted) {
            pending.resolve(null);
            return;
          }
          this.current = null;
          pending.resolve(response);
        } catch (error) {
          if (pending.controller.signal.aborted || this.current !== pending || isAbortError(error)) {
            pending.resolve(null);
            return;
          }
          this.current = null;
          pending.reject(error);
        }
      }
    }

    function isAbortError(error) {
      return error && (error.name === "AbortError" || error.code === "ABORT_ERR");
    }

    module.exports = {
      ...protocol,
      DEFAULT_BROKER_URL,
      DEFAULT_DEBOUNCE_MS,
      DEFAULT_MAX_CONTEXT_CHARS,
      DEFAULT_MAX_COMPLETION_CHARS,
      DEFAULT_DEADLINE_MS,
      defaultClientSettings,
      normalizeBrokerUrl,
      protocolUrl,
      contextAroundText,
      lineCharacterFromOffset,
      createAutocompleteRequest,
      insertTextFromResponse,
      BrokerClient,
      BrokerAutocompleteSession,
    };
  },
  "/obsidian/src/plugin-core.js": function(module, exports, require) {
    "use strict";

    const {
      DEFAULT_BROKER_URL,
      DEFAULT_DEBOUNCE_MS,
      DEFAULT_MAX_CONTEXT_CHARS,
      DEFAULT_MAX_COMPLETION_CHARS,
      DEFAULT_DEADLINE_MS,
      TRIGGER_IDLE,
      BrokerAutocompleteSession,
      BrokerClient,
      contextAroundText,
      createAutocompleteRequest,
      defaultClientSettings,
      insertTextFromResponse,
      lineCharacterFromOffset,
    } = require("../../protocol/src/client.js");

    const CLIENT_NAME = "obsidian";
    const DEFAULT_PLUGIN_VERSION = "0.1.0";

    const DEFAULT_OBSIDIAN_SETTINGS = defaultClientSettings({
      brokerUrl: DEFAULT_BROKER_URL,
      debounceMs: DEFAULT_DEBOUNCE_MS,
      maxContextChars: DEFAULT_MAX_CONTEXT_CHARS,
      maxCompletionChars: DEFAULT_MAX_COMPLETION_CHARS,
      deadlineMs: DEFAULT_DEADLINE_MS,
      pluginVersion: DEFAULT_PLUGIN_VERSION,
    });

    function normalizeObsidianSettings(settings = {}) {
      const overrides = settings && typeof settings === "object" ? settings : {};
      return defaultClientSettings({ ...DEFAULT_OBSIDIAN_SETTINGS, ...overrides });
    }

    function obsidianDocumentUri(file, vaultName = "vault") {
      const filePath = file && file.path ? file.path : "untitled.md";
      const encodedVault = encodeURIComponent(vaultName || "vault");
      const encodedPath = filePath.split("/").map(encodeURIComponent).join("/");
      return `obsidian://vault/${encodedVault}/${encodedPath}`;
    }

    function textFromState(state) {
      if (!state || !state.doc) {
        return "";
      }
      return typeof state.doc.toString === "function" ? state.doc.toString() : String(state.doc);
    }

    function cursorFromState(state) {
      const text = textFromState(state);
      const offset = state && state.selection && state.selection.main
        ? state.selection.main.head
        : 0;
      if (state && state.doc && typeof state.doc.lineAt === "function") {
        const line = state.doc.lineAt(offset);
        return {
          line: Math.max(0, line.number - 1),
          character: offset - line.from,
          offset,
        };
      }
      return lineCharacterFromOffset(text, offset);
    }

    function createRequestFromObsidianState({
      state,
      file,
      vaultName,
      settings,
      documentVersion = 0,
      selectedText = "",
      requestId,
      trigger = TRIGGER_IDLE,
    }) {
      const resolvedSettings = normalizeObsidianSettings(settings);
      const text = textFromState(state);
      const cursor = cursorFromState(state);
      const context = contextAroundText(text, cursor.offset, resolvedSettings.maxContextChars);
      return createAutocompleteRequest({
        requestId,
        clientName: CLIENT_NAME,
        clientVersion: resolvedSettings.pluginVersion || DEFAULT_PLUGIN_VERSION,
        documentUri: obsidianDocumentUri(file, vaultName),
        languageId: "markdown",
        documentVersion,
        cursor,
        context: {
          ...context,
          selected_text: selectedText,
        },
        options: {
          max_chars: resolvedSettings.maxCompletionChars,
          deadline_ms: resolvedSettings.deadlineMs,
          trigger,
        },
      });
    }

    class ObsidianAutocompleteController {
      constructor({ settings, client, session, requestIdFactory } = {}) {
        this.settings = normalizeObsidianSettings(settings);
        this.client = client || new BrokerClient({ brokerUrl: this.settings.brokerUrl });
        this.session = session || new BrokerAutocompleteSession({
          client: this.client,
          debounceMs: this.settings.debounceMs,
        });
        this.requestIdFactory = requestIdFactory;
        this.documentVersion = 0;
        this.suggestion = null;
      }

      cancelStale(reason = "obsidian_state_changed") {
        this.session.cancelCurrent(reason);
        this.suggestion = null;
      }

      async requestSuggestion({ state, file, vaultName, trigger = TRIGGER_IDLE }) {
        const documentVersion = ++this.documentVersion;
        const request = createRequestFromObsidianState({
          state,
          file,
          vaultName,
          settings: this.settings,
          documentVersion,
          requestId: this.requestIdFactory ? this.requestIdFactory() : undefined,
          trigger,
        });
        const cursorOffset = request.cursor.offset;
        let response;
        try {
          response = await this.session.complete(request);
        } catch {
          return null;
        }
        const insertText = insertTextFromResponse(response, request.request_id);
        if (!insertText || documentVersion !== this.documentVersion) {
          return null;
        }
        this.suggestion = {
          requestId: request.request_id,
          from: cursorOffset,
          text: insertText,
          documentVersion,
        };
        return this.suggestion;
      }

      accept(view) {
        if (!this.suggestion || !view || !view.state || !view.state.selection) {
          return false;
        }
        const head = view.state.selection.main.head;
        if (head !== this.suggestion.from) {
          this.cancelStale("cursor_moved_before_accept");
          return false;
        }
        const insertText = this.suggestion.text;
        view.dispatch({
          changes: { from: head, insert: insertText },
          selection: { anchor: head + insertText.length },
        });
        this.suggestion = null;
        return true;
      }
    }

    module.exports = {
      CLIENT_NAME,
      DEFAULT_OBSIDIAN_SETTINGS,
      normalizeObsidianSettings,
      obsidianDocumentUri,
      textFromState,
      cursorFromState,
      createRequestFromObsidianState,
      ObsidianAutocompleteController,
    };
  },
  "/obsidian/src/main.js": function(module, exports, require) {
    "use strict";

    const { Plugin, PluginSettingTab, Setting } = require("obsidian");
    const { EditorView, Decoration, ViewPlugin, WidgetType, keymap } = require("@codemirror/view");
    const { Prec } = require("@codemirror/state");
    const { BrokerClient, TRIGGER_DOCUMENT_CHANGE, TRIGGER_IDLE } = require("../../protocol/src/client.js");
    const {
      DEFAULT_OBSIDIAN_SETTINGS,
      ObsidianAutocompleteController,
      normalizeObsidianSettings,
    } = require("./plugin-core.js");

    class GhostTextWidget extends WidgetType {
      constructor(text) {
        super();
        this.text = text;
      }

      toDOM() {
        const span = document.createElement("span");
        span.className = "autocomplete-alternative-ghost-text";
        span.textContent = this.text;
        return span;
      }

      ignoreEvent() {
        return true;
      }
    }

    function decorationsForSuggestion(suggestion) {
      if (!suggestion) {
        return Decoration.none;
      }
      return Decoration.set([
        Decoration.widget({ widget: new GhostTextWidget(suggestion.text), side: 1 }).range(suggestion.from),
      ]);
    }

    function createAutocompleteEditorExtensions(plugin) {
      let viewPlugin;
      viewPlugin = ViewPlugin.fromClass(
        class AutocompleteAlternativeViewPlugin {
          constructor(view) {
            this.controller = new ObsidianAutocompleteController({
              settings: plugin.settings,
              client: plugin.brokerClient,
            });
            this.decorations = Decoration.none;
            this.requestOrdinal = 0;
            this.request(view, TRIGGER_IDLE);
          }

          update(update) {
            if (!update.docChanged && !update.selectionSet) {
              return;
            }
            this.controller.cancelStale("codemirror_update");
            this.decorations = Decoration.none;
            this.request(update.view, update.docChanged ? TRIGGER_DOCUMENT_CHANGE : TRIGGER_IDLE);
          }

          async request(view, trigger) {
            const ordinal = ++this.requestOrdinal;
            const suggestion = await this.controller.requestSuggestion({
              state: view.state,
              file: plugin.app.workspace.getActiveFile(),
              vaultName: plugin.app.vault.getName ? plugin.app.vault.getName() : "vault",
              trigger,
            });
            if (ordinal !== this.requestOrdinal) {
              return;
            }
            this.decorations = decorationsForSuggestion(suggestion);
            view.dispatch({});
          }

          accept(view) {
            const accepted = this.controller.accept(view);
            if (accepted) {
              this.decorations = Decoration.none;
              view.dispatch({});
            }
            return accepted;
          }
        },
        {
          decorations: (value) => value.decorations,
        },
      );

      const acceptWithTab = Prec.highest(
        keymap.of([
          {
            key: "Tab",
            run: (view) => {
              const pluginValue = view.plugin(viewPlugin);
              return pluginValue ? pluginValue.accept(view) : false;
            },
          },
        ]),
      );

      return [viewPlugin, acceptWithTab, ghostTextTheme()];
    }

    function ghostTextTheme() {
      return EditorView.theme({
        ".autocomplete-alternative-ghost-text": {
          opacity: "0.45",
          fontStyle: "italic",
          pointerEvents: "none",
        },
      });
    }

    class AutocompleteAlternativeSettingTab extends PluginSettingTab {
      constructor(app, plugin) {
        super(app, plugin);
        this.plugin = plugin;
      }

      display() {
        const { containerEl } = this;
        containerEl.empty();

        new Setting(containerEl)
          .setName("Broker URL")
          .setDesc("Local autocomplete broker base URL.")
          .addText((text) => text
            .setValue(this.plugin.settings.brokerUrl)
            .onChange(async (value) => {
              this.plugin.settings.brokerUrl = value || DEFAULT_OBSIDIAN_SETTINGS.brokerUrl;
              this.plugin.brokerClient = new BrokerClient({ brokerUrl: this.plugin.settings.brokerUrl });
              await this.plugin.saveSettings();
            }));

        new Setting(containerEl)
          .setName("Debounce (ms)")
          .setDesc("Delay before sending an autocomplete request after note changes.")
          .addText((text) => text
            .setValue(String(this.plugin.settings.debounceMs))
            .onChange(async (value) => {
              this.plugin.settings.debounceMs = Number(value) || DEFAULT_OBSIDIAN_SETTINGS.debounceMs;
              await this.plugin.saveSettings();
            }));

        new Setting(containerEl)
          .setName("Max context characters")
          .setDesc("Maximum prefix plus suffix characters sent to the broker.")
          .addText((text) => text
            .setValue(String(this.plugin.settings.maxContextChars))
            .onChange(async (value) => {
              this.plugin.settings.maxContextChars = Number(value) || DEFAULT_OBSIDIAN_SETTINGS.maxContextChars;
              await this.plugin.saveSettings();
            }));
      }
    }

    class AutocompleteAlternativeObsidianPlugin extends Plugin {
      async onload() {
        this.settings = normalizeObsidianSettings(await this.loadData());
        this.brokerClient = new BrokerClient({ brokerUrl: this.settings.brokerUrl });
        this.registerEditorExtension(createAutocompleteEditorExtensions(this));
        this.addSettingTab(new AutocompleteAlternativeSettingTab(this.app, this));
      }

      async saveSettings() {
        await this.saveData(this.settings);
      }
    }

    module.exports = AutocompleteAlternativeObsidianPlugin;
    module.exports.createAutocompleteEditorExtensions = createAutocompleteEditorExtensions;
  }
});
const __moduleCache = Object.create(null);

function __normalizeModuleId(moduleId) {
  const parts = [];
  for (const part of String(moduleId).split("/")) {
    if (!part || part === ".") {
      continue;
    }
    if (part === "..") {
      parts.pop();
      continue;
    }
    parts.push(part);
  }
  return `/${parts.join("/")}`;
}

function __moduleDirname(moduleId) {
  const index = moduleId.lastIndexOf("/");
  return index <= 0 ? "/" : moduleId.slice(0, index);
}

function __resolveBundledModule(parentId, specifier) {
  if (!specifier.startsWith(".")) {
    return specifier;
  }
  const baseId = __normalizeModuleId(`${__moduleDirname(parentId)}/${specifier}`);
  for (const candidate of [baseId, `${baseId}.js`, `${baseId}/index.js`]) {
    if (__moduleFactories[candidate]) {
      return candidate;
    }
  }
  throw new Error(`Cannot find bundled module ${specifier} from ${parentId}`);
}

function __loadModule(moduleId) {
  if (!__moduleFactories[moduleId]) {
    return require(moduleId);
  }
  if (__moduleCache[moduleId]) {
    return __moduleCache[moduleId].exports;
  }

  const module = { exports: {} };
  __moduleCache[moduleId] = module;
  __moduleFactories[moduleId](
    module,
    module.exports,
    (specifier) => __loadModule(__resolveBundledModule(moduleId, specifier)),
  );
  return module.exports;
}

module.exports = __loadModule("/obsidian/src/main.js");
